schema = "SeamgrimViewSpecV0"

required_views = [
  "seamgrim.graph.v0:trajectory"
]

required_gauges = [
  "seamgrim.graph.v0:xt",
  "seamgrim.graph.v0:vt",
  "seamgrim.graph.v0:at",
  "seamgrim.table.v0:samples"
]
